language: python
services:
  - mysql
python:
  - "3.4"
env:
  - DJANGO=3.4.3 DJANGO_SETTINGS_MODULE="knowhere.travis_settings"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
before_script:
  - mysql -e 'create database test_knowhere;'
script: python manage.py test