language: python
python:
  - "3.4"

services: mysql

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
before_script:
  - mysql -e 'create database knowhere;'
script: python manage.py test